name: Push to Docker hub
run-name: "Push to docker hub: ${{ github.actor }} üöÄ"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    # env:
    #   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Hello
        run: echo $GITHUB_RUN_NUMBER
      - name: Run Makefile
        env:
            DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ env.DOCKER_PASSWORD }}
        run: |
          make docker publish DOCKER_USERNAME=${{env.DOCKER_USERNAME}} DOCKER_PASSWORD=${{env.DOCKER_PASSWORD}} BUILD_NUMBER=$GITHUB_RUN_NUMBER
      - run: echo "üçè This job's status is ${{ job.status }}."